//
// This file was generated by the JPA Modeler
//
package com.trusty3pl.business.model;

import java.io.Serializable;

/**
 * @author EL KHALYLYBADR
 */
public class VendeurHasAppelOffrePK implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1931334327456906038L;

	private String vendeuridVendeur;

    private String appelOffreAcheteuridAcheteur;

    private String appelOffreProduitidProduit;

    private String etatidEtat;

    public VendeurHasAppelOffrePK() {
    }

    public VendeurHasAppelOffrePK(String vendeuridVendeur, String appelOffreAcheteuridAcheteur, String appelOffreProduitidProduit, String etatidEtat) {
        this.vendeuridVendeur = vendeuridVendeur;
        this.appelOffreAcheteuridAcheteur = appelOffreAcheteuridAcheteur;
        this.appelOffreProduitidProduit = appelOffreProduitidProduit;
        this.etatidEtat = etatidEtat;
    }

    public String getVendeuridVendeur() {
        return this.vendeuridVendeur;
    }

    public void setVendeuridVendeur(String vendeuridVendeur) {
        this.vendeuridVendeur = vendeuridVendeur;
    }

    public String getAppelOffreAcheteuridAcheteur() {
        return this.appelOffreAcheteuridAcheteur;
    }

    public void setAppelOffreAcheteuridAcheteur(String appelOffreAcheteuridAcheteur) {
        this.appelOffreAcheteuridAcheteur = appelOffreAcheteuridAcheteur;
    }

    public String getAppelOffreProduitidProduit() {
        return this.appelOffreProduitidProduit;
    }

    public void setAppelOffreProduitidProduit(String appelOffreProduitidProduit) {
        this.appelOffreProduitidProduit = appelOffreProduitidProduit;
    }

    public String getEtatidEtat() {
        return this.etatidEtat;
    }

    public void setEtatidEtat(String etatidEtat) {
        this.etatidEtat = etatidEtat;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final VendeurHasAppelOffrePK other = (VendeurHasAppelOffrePK) obj;
        if (!java.util.Objects.equals(this.getVendeuridVendeur(), other.getVendeuridVendeur())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getAppelOffreAcheteuridAcheteur(), other.getAppelOffreAcheteuridAcheteur())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getAppelOffreProduitidProduit(), other.getAppelOffreProduitidProduit())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getEtatidEtat(), other.getEtatidEtat())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + (this.getVendeuridVendeur() != null ? this.getVendeuridVendeur().hashCode() : 0);
        hash = 67 * hash + (this.getAppelOffreAcheteuridAcheteur() != null ? this.getAppelOffreAcheteuridAcheteur().hashCode() : 0);
        hash = 67 * hash + (this.getAppelOffreProduitidProduit() != null ? this.getAppelOffreProduitidProduit().hashCode() : 0);
        hash = 67 * hash + (this.getEtatidEtat() != null ? this.getEtatidEtat().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "VendeurHasAppelOffrePK{" + " vendeuridVendeur=" + vendeuridVendeur + ", appelOffreAcheteuridAcheteur=" + appelOffreAcheteuridAcheteur + ", appelOffreProduitidProduit=" + appelOffreProduitidProduit + ", etatidEtat=" + etatidEtat + '}';
    }

}
